# Site title
title: Almighty Couch

# Meta description
description: >
  Almighty Couch is a small, independent studio located in Innsbruck, Austria.
  We specialize in desktop and mobile application development with work expanding to websites,
  user interfaces and marketing material for clients of all sizes on every development platform.

# Permalink for blog posts
permalink: /blog/:title

# Markdown engine
markdown: kramdown

# Code highlightning engine
highlighter: rouge

# Assets pipline
assets:
  sources:
    - _assets/fonts
    - _assets/images

# Dependencies
gems:
  - bourbon
  - neat
  - jekyll-assets
  - jekyll-feed

# Excluded files
exclude:
  - Gemfile
  - Gemfile.lock
